import cx_Oracle
con=cx_Oracle.connect("Bank/12345678")
cur=con.cursor()
print(con.version)
cur.execute("create table customer (acc_no varchar2(10) primary key,name varchar2(20) not null, phone_no number(10) not null,e_mail varchar2(40) not null,address varchar2(50) not null,cust_type varchar2(10) not null,bal number(10) not null,security_money number(10))")
#cur.execute("create table balance (acc_no varchar2(10) primary key, bal number(10))")
cur.execute("create table login (username varchar2(10),password varchar2(15))")
cur.execute("create table tranx (acc_no varchar2(10),tranx_date date not null,amount number(10) not null,type varchar2(2) not null)")
cur.execute("insert into login values('prince','prince')")
cur.execute("insert into login values('nitesh','nitesh')")
cur.execute("insert into login values('amitesh','amitesh')")
cur.execute("insert into login values('arima','arima')")
cur.execute("insert into login values('aanchal','aanchal')")
cur.execute("insert into customer values('s1000','prince',9876543210,'prince@gmail.com','jupiter','R',5000,'')")
cur.execute("insert into customer values('c1000','amitesh',9876543210,'rjamitesh@gmail.com','temporary','R',5000,'')")
con.commit()
